name: CI (Release)
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish single-file EXE
        run: dotnet publish -p:PublishSingleFile=true -p:SelfContained=false -p:CommitHash=${{ github.sha }} -p:CommitRef=${{ github.ref_type }}/${{ github.ref_name }} -r win-x64 -c Release ./Bloxstrap/Bloxstrap.csproj

      - name: Upload Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: Froststrap (Release) (${{ github.sha }})
          path: .\Bloxstrap\bin\Release\net6.0-windows\win-x64\publish\*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Froststrap (Release) (${{ github.sha }})
          path: release

      - name: Sign with SignPath
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '837ad744-6d64-4d44-94ef-65a9a2d09399'
          project-slug: 'Froststrap'
          signing-policy-slug: 'release-signing'
          artifact-configuration-slug: 'Initial version'
          github-artifact-id: '${{ needs.build.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: 'release'

      - name: Rename binaries
        run: mv release/Bloxstrap.exe Froststrap-${{ github.ref_name }}.exe

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: Froststrap-${{ github.ref_name }}.exe
          name: Froststrap ${{ github.ref_name }}
          fail_on_unmatched_files: true

  release-test:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/release-test')
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Froststrap (Release) (${{ github.sha }})
          path: release

      - name: Sign with SignPath (Test)
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '837ad744-6d64-4d44-94ef-65a9a2d09399'
          project-slug: 'Froststrap'
          signing-policy-slug: 'test-signing'
          artifact-configuration-slug: 'Initial version'
          github-artifact-id: '${{ needs.build.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: 'release'

      - name: Rename binaries
        run: mv release/Bloxstrap.exe Froststrap-${{ github.ref_name }}.exe

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: Froststrap-${{ github.ref_name }}.exe
          name: Froststrap ${{ github.ref_name }}
          fail_on_unmatched_files: true