name: Build & Sign Froststrap

on:
  push:
    branches:
      - main

jobs:
  build-and-sign:
    runs-on: windows-latest

    steps:
      # 1. Checkout repo including submodules
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      # 2. Publish single-file EXE (main project only)
      - name: Publish single-file EXE
        run: |
          dotnet publish Bloxstrap\Bloxstrap.csproj `
            --configuration Release `
            /p:PublishSingleFile=true `
            /p:IncludeAllContentForSelfExtract=true `
            /p:RuntimeIdentifier=win-x64 `
            --output "${{ github.workspace }}\publish"

      # 3. Package the EXE
      - name: Package EXE
        run: |
          powershell Compress-Archive -Path "${{ github.workspace }}\publish\Bloxstrap.exe" -DestinationPath Froststrap.zip

      # 4. Upload unsigned artifact
      - name: Upload unsigned artifact
        id: upload-unsigned
        uses: actions/upload-artifact@v4
        with:
          name: froststrap-unsigned
          path: Froststrap.zip

      # 5. Submit signing request to SignPath
      - name: Request SignPath signing
        uses: signpath/github-action-submit-signing-request@v1
        with:
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          organization-id: 837ad744-6d64-4d44-94ef-65a9a2d09399
          project-slug: Froststrap
          signing-policy-slug: test-signing
          github-artifact-id: ${{ steps.upload-unsigned.outputs.artifact-id }}
          wait-for-completion: true
          output-artifact-directory: signed